name: 'Automations updating ssl-certs'

on:
  push:
    branches:
    - main
  pull_request:

  #schedule:
  #  - cron: "*/5 * * * *"

jobs:
  preparing_terraform_env:
    name: 'Install terraform'
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
      CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    environment: production
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      

  validate_terraform_env:
    name: 'Validate terraform'
    runs-on: ubuntu-latest
    needs: preparing_terraform_env

    steps:
    - name: Terraform Validate
      run: terraform validate


  terraform_plan:
    name: 'Terraform plan'
    runs-on: ubuntu-latest
    needs: validate_terraform_env
    env:
      CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
      CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Plan
      run: terraform plan -out "planfile"
      
    - name: Uploads Аrtifacts Planfile
      uses: actions/upload-artifact@v2
      with:
        name: planfile
        path: ./planfile

  terraform_apply:
    name: 'Terraform apply'
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
      CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    needs: terraform_plan

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Downloads Аrtifacts Planfile
      uses: actions/download-artifact@v2
      with:
        name: planfile
        path: ./planfile
        
    - name: show files
      run: pwd && ls -la

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -input=false "/home/runner/work/receive_ssl/receive_ssl/planfile/planfile"
      
    - name: Upload ssl-certs
      uses: actions/upload-artifact@v2
      with:
        name: certificates
        path: ./certificates/*
  
  deploy_certs:
    name: 'Deploy new certs to prod'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    needs: terraform_apply
    
    steps:
    #- name: Downloas prod repository 
    #  uses: actions/checkout@master
    #    with:
    #    repository: HumeniukDenys/certs
    - name: Download other repo
      run: |
        git remote add origin git@github.com:HumeniukDenys/certs.git
        git branch -M main
        git push -u origin main
    
    - name: Show files
      run: pwd && ls -la
      
    - name: Downloads Аrtifacts Planfile
      uses: actions/download-artifact@v2
      with:
        name: certificates
        path: /tmp/certificates/.
        
    - name: Show files in tmp
      run: pwd && ls -la
